version: '3.7'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      # To access from outside too, from tooling.
      - "3306:3306"
    volumes:
      - tasks-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=super-random-password-123456
      - MYSQL_USER=tasksapp
      - MYSQL_PASSWORD=another-super-random-password
      - MYSQL_DATABASE=tasksdb

  tasks:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"
    environment:
      - ConnectionStrings__UserTasks=Host=db;User=tasksapp;Protocol=Socket;Password=another-super-random-password;Database=tasksdb
    ports:
      - "80:80"

volumes:
  tasks-db-data:
